import os
import json

USER_ROWS_TEXT = """
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"What is the total net revenue from completed orders?\""}, {"role": "assistant", "content": "```sql\\nSELECT SUM(net_amount) AS total_revenue FROM orders WHERE order_status = 'completed';\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"Show the top 5 categories by total revenue.\""}, {"role": "assistant", "content": "```sql\\nSELECT category, SUM(net_amount) AS total_revenue FROM orders GROUP BY category ORDER BY total_revenue DESC LIMIT 5;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"What percentage of orders were returned?\""}, {"role": "assistant", "content": "```sql\\nSELECT ROUND(100.0 * SUM(CASE WHEN order_status = 'returned' THEN 1 ELSE 0 END) / COUNT(*), 2) AS return_pct FROM orders;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"List distinct payment methods used.\""}, {"role": "assistant", "content": "```sql\\nSELECT DISTINCT payment_method FROM orders;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"What is the monthly revenue trend for 2024?\""}, {"role": "assistant", "content": "```sql\\nSELECT DATE_TRUNC('month', CAST(order_date AS DATE)) AS month, SUM(net_amount) AS monthly_revenue FROM orders WHERE YEAR(CAST(order_date AS DATE)) = 2024 GROUP BY month ORDER BY month;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"Show categories with average order value greater than 500, sorted descending.\""}, {"role": "assistant", "content": "```sql\\nSELECT category, AVG(net_amount) AS avg_order_value FROM orders GROUP BY category HAVING AVG(net_amount) > 500 ORDER BY avg_order_value DESC;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"Rank orders within each region by net_amount, highest first.\""}, {"role": "assistant", "content": "```sql\\nSELECT order_id, region, net_amount, RANK() OVER (PARTITION BY region ORDER BY net_amount DESC) AS region_rank FROM orders;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"Show a running cumulative revenue total ordered by order_date.\""}, {"role": "assistant", "content": "```sql\\nSELECT order_id, order_date, net_amount, SUM(net_amount) OVER (ORDER BY order_date) AS cumulative_revenue FROM orders;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"What is the number of days between order_date and ship_date for each order?\""}, {"role": "assistant", "content": "```sql\\nSELECT order_id, DATEDIFF('day', CAST(order_date AS DATE), CAST(ship_date AS DATE)) AS days_to_ship FROM orders;\\n```"}]}
{"messages": [{"role": "system", "content": "You are an expert DuckDB SQL Data Analyst writing read-only SELECT queries. Use ONLY the tables and columns provided in the database schema context. Return ONLY the SQL query inside ```sql ... ``` code block."}, {"role": "user", "content": "Database Schema:\\nTable `orders`: order_id (INT), customer_id (INT), region (VARCHAR), category (VARCHAR), subcategory (VARCHAR), net_amount (DECIMAL), discount_amount (DECIMAL), quantity (INT), order_status (VARCHAR), payment_method (VARCHAR), order_date (DATE), ship_date (DATE)\\n\\nQuestion: \"Find customers whose total spend is above the overall average total spend per customer.\""}, {"role": "assistant", "content": "```sql\\nSELECT customer_id, SUM(net_amount) AS total_spend FROM orders GROUP BY customer_id HAVING SUM(net_amount) > (SELECT AVG(cust_total) FROM (SELECT SUM(net_amount) AS cust_total FROM orders GROUP BY customer_id) AS sub);\\n```"}]}
"""

def append_user_rows(dataset_path: str = "data/finetune_dataset.jsonl"):
    lines = [line.strip() for line in USER_ROWS_TEXT.strip().split("\n") if line.strip()]
    
    with open(dataset_path, "a", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
            
    print(f"✅ Successfully appended user-written training examples to '{dataset_path}'.")

if __name__ == "__main__":
    append_user_rows()
